[package]
edition = "2021"
name = "deepnest_svg-preprocessor"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi.workspace = true
napi-derive.workspace = true
usvg.workspace = true

[build-dependencies]
napi-build.workspace = true

[profile.release]
lto = true
strip = "symbols"
